### ISSUE TITLE
AtomicTaskSpace crashes SampleSort

### ISSUE THREAD

**Issue by dialecticDolt** [ut-parla/parla-experimental#125]
Changing TaskSpace to AtomicTaskSpace crashes sample sort. 
If it a scoping issue?

**Comment by ShreyaTalati** [comment]
I tested code for AtomicTaskSpace for sample sort - https://github.com/ut-parla/parla-experimental/commit/28c39a8f835e6b18effdf454441edffa4f9c9845
and it worked out fine for me;
![image](https://github.com/ut-parla/parla-experimental/assets/41751613/2d675d31-73d0-4c26-9c15-5c7e3c63b3b1)

**Comment by dialecticDolt** [comment]
oh that's odd, maybe we accidentally fixed it when making other changes? Or it might have been a compilation issue resolved by the new flags? 

Try a run with n >> 40 though (I suggest millions) just to check it isn't only showing for large problems.

**Comment by ShreyaTalati** [comment]
Also, works fine if n is in millions:
![image](https://github.com/ut-parla/parla-experimental/assets/41751613/f43fe74e-397d-4aeb-8958-ec0fb53981dc)
The changes made with reference to AtomicTaskSpace are these according to the git history:
https://github.com/ut-parla/parla-experimental/commit/83dfe9c91b0daf60d2b05d2672f2dc5247e607d3
I reverted this on my instance to check and the sample sort still worked.
